server:
  port: 9010
spring:
  application:
    name: tensquare-friend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.230.100:3306/tensquare_friend?characterEncoding=utf-8
    username: root
    password: "123456"
  jpa:
    database: mysql
    show-sql: true
  rabbitmq:
    host: 192.168.230.100
jwt:
  config:
    key: itcast
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true