server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 192.168.230.100
  rabbitmq:
    host: 192.168.230.100
aliyun:
  sms:
    accessKeyId: LTAI4Fex8BW9ZSMr8cEzHcCN
    accessKeySecret: G20NdWIFHd01PXZQ2H5ZuFlZnBBJoF
    template_code: SMS_175070234
    sign_name: tensquare