server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 192.168.230.100
      database: spitdb
  redis:
    host: 192.168.230.100
  rabbitmq:
    host: 192.168.230.100